<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Rupert Benbrook</Authors>
    <Description>https://github.com/rupertbenbrook/cosmosdb-json-patch</Description>
    <Copyright>Copyright © 2025 Rupert Benbrook</Copyright>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerfileFile>..\Dockerfile</DockerfileFile>
    <DockerfileContext>..</DockerfileContext>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="JsonPatch.Net" Version="3.3.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.54.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
